### ISSUE TITLE
Apply LAME --gain to Export

### ISSUE THREAD

**Issue by PwhiteFea3d** [jherby2k/AudioWorks#26]
I'm looking for the analogy to the -Setting @{ApplyGain = "Track"} option from the retired PowerShell Audio.  I apologize for resorting to logging an issue, just haven't found an alternate path after my Google Fu failed me.

**Comment by jherby2k** [comment]
`Export-AudioFile -Encoder LameMP3 -ApplyGain Track`

FYI, there is tab-completion for dynamic parameters. So, you can just say `-Encoder LameMP3` and then tab through the available settings.
