### ISSUE TITLE
Is there possible Path-Issue causing this ?

### ISSUE THREAD

**Issue by nonspin** [jherby2k/AudioWorks#27]
In Theory, If i would:  

`Get-AudioFile .\input.flac | Export-AudioFile -Encoder LameMP3 .  ` 

and assuming the conversion was successful, shouldn't: 

 `Get-AudioFile .\input.mp3 | Export-AudioFile -Encoder <Any> .  `

work ?  
Every Encoder <Any> returns:

` "Export-AudioFile: No supporting decoders are available."`  

.. Yes, i can assure you, that all Decoders are present. 
It seems like a path is misdirected, because 
when using the UI (properly compiled),  
the GUI shows - i can do everything BUT start/initiate the encoding-process  
.. Not showing any errors - like it won't, 
because the path is not set properly ??

**Comment by jherby2k** [comment]
Issue is that there is indeed no MP3 decoder. I didn't include decoders for lossy formats because transcoding isn't advisable. Open to adding them (with a warning) if there is legit demand for it.

**Comment by nonspin** [comment]
Now, that i know there's no decoder, it's fine by me - not necessary to add a decoder.

About the UI-App, is it supposed to not-work (like not start the conversion no matter what format)
or am i missing something ?
All other features work (like Replay-Gain), but doesnt encode/convert.
Again, like the path to the encoders is not set. The reason i'm asking is because
there are to 2 folders in use as i see it:

```
..AppData\Local\AudioWorks (with /Extensions and all the Extensions)
..AppData\Local\AudioWorks (with settings.json)
```
Isn't there a more logical way ?

**Comment by jherby2k** [comment]
UI is incomplete - about the only thing not working is encoding :). I need to add a wizard.
