### ISSUE TITLE
wav a-law is not recognizedby get-audiofile

### ISSUE THREAD

**Issue by darwincr** [jherby2k/AudioWorks#32]
I Can not convert wav a-law audio files to .mp3
The proccess fails when the get-audiofile fails with error:

```
Get-AudioFile : Unable to decode '<FilePath.wav>' with any loaded extension.
At line:1 char:1
+ Get-AudioFile -Path "<FilePath.wav>"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (<FilePath.wav>:String) [Get-AudioFile], AudioUnsupportedException
    + FullyQualifiedErrorId : AudioUnsupportedException,AudioWorks.Commands.GetAudioFileCommand
```

![AudioInfo](https://user-images.githubusercontent.com/19042620/104494113-1f610800-562a-11eb-8f0d-fdac3db6af05.PNG)

[AudioFile.wav.zip](https://github.com/jherby2k/AudioWorks/files/5810465/AudioFile.wav.zip)

**Comment by jherby2k** [comment]
Yup, a-law is currently unsupported by the Wave extension. Only LPCM so far.

**Comment by jherby2k** [comment]
Try it now - i've added a-law and µ-law decoding.

**Comment by jherby2k** [comment]
Added feature, no feedback - assuming ok

**Comment by darwincr** [comment]
Tested ok,
issue is resolved
thanks

**Comment by darwincr** [comment]
issue is resolved
thanks
